import { NextResponse } from 'next/server';

const MOCK_PRODUCTS = [
    // 1. Nella Muthu Vilas Special (Signature)
    {
        id: 'nmv-1',
        name: 'Tirunelveli Halwa',
        description: 'Our signature wheat halwa, dripping with pure ghee and cashews.',
        price: 180,
        weight: '250g',
        image: '/images/products/halwa.jpg',
        specialCategory: 'NMV_SPECIAL',
        tags: 'Chef’s Choice,House Special',
        available: true,
        tradition: 'Signature',
    },
    {
        id: 'nmv-2',
        name: 'Ghee Mysore Pak',
        description: 'Melt-in-your-mouth texture with rich ghee flavor.',
        price: 200,
        weight: '250g',
        image: '/images/products/mysorepak.jpg',
        specialCategory: 'NMV_SPECIAL',
        tags: 'House Special,Premium',
        available: true,
        tradition: 'Royal',
    },

    // 2. Top Picks (Most Ordered)
    {
        id: 'top-1',
        name: 'Motichoor Laddu',
        description: 'Fine boondi laddu made with pure ghee.',
        price: 150,
        weight: '250g',
        image: '/images/products/laddu.jpg',
        specialCategory: 'TOP_PICKS',
        tags: 'Most Ordered,Popular Today',
        available: true,
        tradition: 'Classic',
    },
    {
        id: 'top-2',
        name: 'Mini Jangiri',
        description: 'Juicy swirls of fermented urad dal batter fried to perfection.',
        price: 140,
        weight: '250g',
        image: '/images/products/jangiri.jpg',
        specialCategory: 'TOP_PICKS',
        tags: 'Popular Today',
        available: true,
        tradition: 'Festive',
    },

    // 3. Festival Favourite
    {
        id: 'fest-1',
        name: 'Adhirasam',
        description: 'Traditional fermented rice and jaggery donut.',
        price: 130,
        weight: '5 pcs',
        image: '/images/products/adhirasam.jpg',
        specialCategory: 'FESTIVAL_FAVOURITE',
        tags: 'Festive Special,Seasonal Delight',
        available: true,
        tradition: 'Village Special',
    },
    {
        id: 'fest-2',
        name: 'Kai Murukku',
        description: 'Hand-twisted crunchy rice spirals.',
        price: 120,
        weight: '200g',
        image: '/images/products/murukku.jpg',
        specialCategory: 'FESTIVAL_FAVOURITE',
        tags: 'Seasonal Delight,Crispy',
        available: true,
        tradition: 'Savoury',
    },

    // 4. Customer Favourite
    {
        id: 'cust-1',
        name: 'Badusha',
        description: 'Flaky pastry donuts glazed in sugar syrup.',
        price: 160,
        weight: '250g',
        image: '/images/products/badusha.jpg',
        specialCategory: 'CUSTOMER_FAVOURITE',
        tags: 'Loved by Customers,Best Rated',
        available: true,
        tradition: 'North-South Fusion',
    },
    {
        id: 'cust-2',
        name: 'Chandrakala',
        description: 'Crispy pastry filled with sweet khoya and dry fruits.',
        price: 190,
        weight: '250g',
        image: '/images/products/chandrakala.jpg',
        specialCategory: 'CUSTOMER_FAVOURITE',
        tags: 'Best Rated,Rich',
        available: true,
        tradition: 'Royal',
    },

    // 5. All-Time Classics
    {
        id: 'clas-1',
        name: 'Soan Papdi',
        description: 'Flaky and crisp flaky sweet with cardamom.',
        price: 140,
        weight: '200g',
        image: '/images/products/soanpapdi.jpg',
        specialCategory: 'ALL_TIME_CLASSICS',
        tags: 'Traditional,Timeless Recipe',
        available: true,
        tradition: 'Classic',
    },
    {
        id: 'clas-2',
        name: 'Mixture',
        description: 'Spicy mix of boondi, omapodi, nuts, and curry leaves.',
        price: 100,
        weight: '250g',
        image: '/images/products/mixture.jpg',
        specialCategory: 'ALL_TIME_CLASSICS',
        tags: 'Traditional,Spicy',
        available: true,
        tradition: 'Savoury',
    },
    {
        id: 'clas-3',
        name: 'Rava Laddu',
        description: 'Semolina balls made with ghee, sugar, and cashews.',
        price: 150,
        weight: '250g',
        image: '/images/products/ravaladdu.jpg',
        specialCategory: 'ALL_TIME_CLASSICS',
        tags: 'Timeless Recipe,Home Style',
        available: true,
        tradition: 'Classic',
    },
    {
        id: 'clas-4',
        name: 'Palkova',
        description: 'Rich, caramelized milk sweet made from pure cow milk.',
        price: 180,
        weight: '200g',
        image: '/images/products/palkova.jpg',
        specialCategory: 'ALL_TIME_CLASSICS',
        tags: 'Milk Sweet,Traditional',
        available: true,
        tradition: 'Srivilliputhur',
    },
    {
        id: 'clas-5',
        name: 'Ribbon Pakoda',
        description: 'Crunchy ribbon-shaped savoury snack.',
        price: 90,
        weight: '200g',
        image: '/images/products/ribbon.jpg',
        specialCategory: 'ALL_TIME_CLASSICS',
        tags: 'Savoury,Crispy',
        available: true,
        tradition: 'Festival Snack',
    },
];

export async function GET() {
    return NextResponse.json(MOCK_PRODUCTS);
}
