import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import bcrypt from 'bcryptjs';
import { prisma } from '../utils/prisma.js';

const publicDir = path.resolve(process.cwd(), 'public');
function resolveImage(image) {
  if (!image) return '/images/placeholder_classy.svg';
  const base = path.basename(image);
  for (const candidate of [path.join(publicDir, image.replace(/^\/+/, '')), path.join(publicDir, 'images', 'products', base), path.join(publicDir, 'images', base)]) {
    if (fs.existsSync(candidate)) return `/${path.relative(publicDir, candidate).replaceAll('\\\\', '/')}`;
  }
  return image;
}
function publicProduct(product) { return { ...product, image: resolveImage(`/images/products/${path.basename(product.image || '')}`) }; }
function publicOrderId() { return `NMV-${new Date().toISOString().slice(0, 10).replaceAll('-', '')}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`; }
function otp() { return String(Math.floor(100000 + Math.random() * 900000)); }
async function retry(fn, attempts = 3) { try { return await fn(); } catch (error) { if (attempts <= 1) throw error; await new Promise((resolve) => setTimeout(resolve, 100 * (4 - attempts))); return retry(fn, attempts - 1); } }

export const service = {
  health: async () => { const start = Date.now(); let database = 'UP'; try { await prisma.$queryRaw`SELECT 1`; } catch { database = 'DOWN'; } return { status: database === 'UP' ? 'ok' : 'error', timestamp: new Date().toISOString(), uptime: process.uptime(), database, latency: `${Date.now() - start}ms` }; },
  products: async (admin = false) => (await prisma.product.findMany(admin ? { orderBy: { createdAt: 'desc' } } : { where: { available: true } })).map(publicProduct),
  branches: async () => prisma.branch.findMany({ orderBy: { name: 'asc' } }),
  ordersForUser: async (userId) => { const user = await prisma.user.findUnique({ where: { id: userId }, select: { id: true } }); if (!user) return null; const orders = await prisma.order.findMany({ where: { userId }, include: { branch: true, items: { include: { product: true } } }, orderBy: { createdAt: 'desc' } }); return orders.map(({ pickupOtpHash, ...order }) => order); },
  createOrder: async (user, body) => { const { branchId, items, totalAmount, orderType } = body; if (!branchId || !items?.length || !totalAmount) return { error: 'Missing required fields', status: 400 }; const dbUser = await prisma.user.findUnique({ where: { email: user.email }, select: { id: true } }); if (!dbUser) return { error: 'User not found in database. Please relogin.', status: 401 }; if (!await prisma.branch.findUnique({ where: { id: branchId }, select: { id: true } })) return { error: 'Invalid Branch selected. Please ensure the branch exists.', status: 400 }; for (const item of items) if (!await prisma.product.findUnique({ where: { id: item.productId }, select: { id: true } })) return { error: `Item '${item.name}' is no longer available (ID mismatch). Please clear your cart and re-add items.`, status: 400 }; const isCash = body.paymentMethod === 'CASH'; const plainOtp = isCash ? otp() : null; const order = await retry(() => prisma.order.create({ data: { simpleId: `NMV-${Math.floor(100000 + Math.random() * 900000)}`, publicOrderId: publicOrderId(), userId: dbUser.id, branchId, totalAmount, status: isCash ? 'CONFIRMED' : 'PENDING_PAYMENT', orderType: orderType || 'PRE_ORDER', paymentMethod: body.paymentMethod || 'CASH', pickupOtpHash: plainOtp ? bcrypt.hashSync(plainOtp, 10) : null, pickupTime: new Date(body.pickupTime || Date.now()), items: { create: items.map((item) => ({ productId: item.productId, quantity: item.quantity, price: item.price })) } } })); return { order: { ...order, otp: plainOtp } }; },
  createFeedback: async (userId, { orderId, rating, comment }) => { if (!orderId || !rating || rating < 1 || rating > 5) return { error: 'Invalid feedback data', status: 400 }; const order = await prisma.order.findUnique({ where: { id: orderId } }); if (!order) return { error: 'Order not found', status: 404 }; if (order.userId !== userId) return { error: 'Unauthorized', status: 401 }; if (order.status !== 'COMPLETED') return { error: 'Feedback can only be submitted for completed orders', status: 400 }; const prior = await prisma.auditLog.findFirst({ where: { userId, action: 'SUBMIT_FEEDBACK', details: { contains: `\"orderId\":\"${orderId}\"` } } }); if (prior) return { error: 'Feedback already submitted for this order', status: 400 }; const [feedback] = await prisma.$transaction([prisma.feedback.create({ data: { userId, rating: parseInt(rating), comment } }), prisma.auditLog.create({ data: { userId, action: 'SUBMIT_FEEDBACK', details: JSON.stringify({ orderId, rating, comment }) } })]); return { message: 'Feedback submitted successfully', feedback }; },
  adminStats: async (branchId, manager) => { const filter = manager ? { branchId } : (branchId ? { branchId } : {}); const now = new Date(); const start = new Date(now.getFullYear(), now.getMonth(), now.getDate()); const [todayCount, pendingCount, upcomingPreOrders, todayRevenue] = await Promise.all([prisma.order.count({ where: { ...filter, createdAt: { gte: start } } }), prisma.order.count({ where: { ...filter, status: { in: ['RECEIVED', 'PREPARING'] } } }), prisma.order.count({ where: { ...filter, orderType: 'PRE_ORDER', pickupTime: { gt: now }, status: { not: 'CANCELLED' } } }), prisma.order.aggregate({ _sum: { totalAmount: true }, where: { ...filter, status: 'COMPLETED', updatedAt: { gte: start } } })]); return { todayCount, pendingCount, upcomingPreOrders, todayRevenue: todayRevenue._sum.totalAmount || 0 }; },
  adminOrders: async (query, manager) => { const { type, status } = query; const branchId = manager.branchId || query.branchId; const where = { ...(type ? { orderType: type } : {}), ...(branchId ? { branchId } : {}), ...(status ? { status } : {}) }; return prisma.order.findMany({ where, include: { user: { select: { name: true, email: true, phone: true } }, branch: true, items: { include: { product: true } } }, orderBy: { createdAt: 'desc' } }); },
  updateOrder: async (id, status) => prisma.order.update({ where: { id }, data: { status }, include: { user: { select: { name: true, email: true } }, branch: true } }),
  updateBranch: async (body) => prisma.branch.update({ where: { id: body.id }, data: { isActive: body.isActive, status: body.status, timings: body.timings } }),
  createProduct: async (body) => prisma.product.create({ data: { name: body.name, price: parseInt(body.price), weight: body.weight || '', description: body.description || '', image: body.image || '/images/placeholder.jpg', tradition: body.tradition || '', specialCategory: body.specialCategory || null, tags: body.tags || null, available: true } }),
  updateProduct: async (body) => prisma.product.update({ where: { id: body.id }, data: { price: body.price, available: body.available, tags: body.tags, specialCategory: body.specialCategory } }),
  logs: async () => { const logs = await prisma.auditLog.findMany({ orderBy: { createdAt: 'desc' }, take: 100 }); return Promise.all(logs.map(async (log) => ({ ...log, user: log.userId ? await prisma.user.findUnique({ where: { id: log.userId }, select: { name: true, email: true } }) : null }))); },
  feedback: async (query) => { const where = { ...(query.minRating ? { rating: { gte: parseInt(query.minRating) } } : {}), ...(query.userId ? { userId: query.userId } : {}) }; const feedbacks = await prisma.feedback.findMany({ where, orderBy: { createdAt: 'desc' } }); const enriched = await Promise.all(feedbacks.map(async (feedback) => ({ ...feedback, user: feedback.userId ? await prisma.user.findUnique({ where: { id: feedback.userId }, select: { name: true, email: true } }) : null }))); const stats = await prisma.feedback.aggregate({ _avg: { rating: true }, _count: { id: true } }); return { feedbacks: enriched, stats: { averageRating: stats._avg.rating || 0, totalFeedback: stats._count.id || 0 } }; },
  salesReport: async (days) => { const start = new Date(); start.setDate(start.getDate() - days); start.setHours(0, 0, 0, 0); const orders = await prisma.order.findMany({ where: { createdAt: { gte: start }, status: 'COMPLETED' }, select: { createdAt: true, totalAmount: true }, orderBy: { createdAt: 'asc' } }); const grouped = {}; for (const order of orders) { const date = order.createdAt.toISOString().slice(0, 10); grouped[date] ||= { date, revenue: 0, orders: 0 }; grouped[date].revenue += order.totalAmount; grouped[date].orders += 1; } return Object.values(grouped); },
  productReport: async () => { const items = await prisma.orderItem.findMany({ where: { order: { status: 'COMPLETED' } }, include: { product: { select: { name: true } } } }); const grouped = {}; for (const item of items) { const name = item.product.name; grouped[name] ||= { name, volume: 0, revenue: 0 }; grouped[name].volume += item.quantity; grouped[name].revenue += item.price * item.quantity; } return Object.values(grouped).sort((a, b) => b.volume - a.volume); },
  branchReport: async () => { const branches = await prisma.branch.findMany({ include: { orders: { where: { status: 'COMPLETED' }, select: { totalAmount: true } } } }); return branches.map((branch) => ({ id: branch.id, name: branch.name, totalOrders: branch.orders.length, totalRevenue: branch.orders.reduce((sum, order) => sum + order.totalAmount, 0) })); },
};
